SNOWFLAKE_ACCOUNT =  ${{ secrets.SNOWFLAKE_ACCOUNT }}
SNOWFLAKE_USERNAME = ${{ secrets.SNOWFLAKE_USERNAME }}
SNOWFLAKE_ROLE = ${{ secrets.SNOWFLAKE_ROLE }}
SNOWFLAKE_WAREHOUSE = ${{ secrets.SNOWFLAKE_WAREHOUSE }}
private-key = ${{ secrets.SNOWFLAKE_PRIVATE_KEY}}
private_key_file_pwd = ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE}}
SNOWFLAKE_DATABASE = ${{ secrets.SNOWFLAKE_DATABASE }}

