name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'Migrations/**'
  workflow_dispatch:

env:
  SNOWFLAKE_USER:  ${{vars.SNOWFLAKE_USER}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Print Snowflake Account
        run: |
          echo "Printing Snowflake Account"
          echo "${{ secrets.SNOWFLAKE_ACCOUNT }}"

      - name: Install schemachange and snowflake connector
        run: |
          pip install --upgrade snowflake-connector-python schemachange

      - name: Decode private key
        run: |
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > decoded_private_key.p8
          chmod 600 decoded_private_key.p8

      - name: Create connections.toml
        run: |
          cat <<EOF > connections.toml
          [connections.connections]
          account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
          user = "${{ env.SNOWFLAKE_USER }}"
          role = "${{ secrets.SNOWFLAKE_ROLE }}"
          warehouse = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
          database = "${{ secrets.SNOWFLAKE_DATABASE }}"
          schema = "${{ secrets.SNOWFLAKE_SCHEMA }}"
          private-key = "$(cat decoded_private_key.p8)"
          private_key_file_pwd = "${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}"
          EOF

      - name: Print connections.toml
        run: cat connections.toml

      - name: Secure connections.toml permissions
        run: chmod 600 connections.toml

      - name: Run schemachange
        run: schemachange -f Migrations --connections-file-path connections.toml --connection-name connections
