name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events to the "master" branch from the "non_prod" branch
  push:
    branches:
      - master
    paths:
      - '**'
    branches-ignore:
      - non_prod

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      SF_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SF_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SF_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SF_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SF_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SF_TRANSFORMATION_SCHEMA: ${{ secrets.SNOWFLAKE_TRANSFORMATION_SCHEMA }}
      SF_CONSUMPTION_SCHEMA: ${{ secrets.SNOWFLAKE_CONSUMPTION_SCHEMA }}
      PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
      PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install schemachange
      - name: Install schemachange
        run: |
          echo "Step 1: Installing schemachange"
          pip install snowflake-connector-python
          pip install schemachange==3.7.0

      # Run schemachange
      - name: Run schemachange
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/Migrations -a $SF_ACCOUNT -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table --vars '{"SF_DATABASE": "${{env.SF_DATABASE}}", "SF_SCHEMA": "${{env.SF_SCHEMA}}","SF_TRANSFORMATION_SCHEMA": "${{env.SF_TRANSFORMATION_SCHEMA}}","SF_CONSUMPTION_SCHEMA": "${{env.SF_CONSUMPTION_SCHEMA}}"}' --private-key-path $PRIVATE_KEY --private-key-passphrase $PRIVATE_KEY_PASSPHRASE
